<?php
/*
 * This file belongs to the YIT Framework.
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE (GPL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 */

return array(

    'border-1-top' =>   '.single-product.woocommerce div.product div.summary div[itemprop="description"],
                        .blog.small .yit_post_meta,
                        .blog.big .yit_post_meta,
                        .single-product.woocommerce div.product div.summary p.price,
                        .single-product.woocommerce div.product div.summary form.cart,
                        #payment,
                        .woocommerce table.shop_table.order_details tfoot tr:last-child,
                        .woocommerce-page table.shop_table.my_account_orders thead,
                        .testimonial-wrapper .testimonial-rating',

    'border-1-bottom' =>    '.widget h3,
                            #product-box form.cart,
                            #product-box .border.group p.price,
                            .woocommerce-tabs ul.tabs,
                            .blog.big.single .yit_post_content.title,
                            .woocommerce-tabs #comments ol.commentlist li .comment-text,
                            #my-account-sidebar ul li,
                            .widget.widget_recent_entries ul li,
                            .widget.widget_recent_comments ul li,
                            .widget.widget_categories > ul > li,
                            .widget_product_categories ul.product-categories > li,
                            .sidebar .widget.widget_nav_menu ul.menu > li,
                            .woocommerce ul.product_list_widget li,
                            .widget.yit_products_category ul.product_list_widget li,
                            .woocommerce table.shop_table.cart tbody,
                            #yith-wcwl-form table.shop_table tbody,
                            .woocommerce .cart-collaterals .cart_totals tbody tr.shipping,
                            #order_review table tbody,
                            #order_review table tfoot tr.shipping,
                            #payment li,
                            .woocommerce table.shop_table.order_details thead,
                            .woocommerce table.shop_table.order_details tbody,
                            .woocommerce-page table.shop_table.my_account_orders thead,
                            .widget.woocommerce.widget_layered_nav ul.yith-wcan-list li,
                            .contact-info ul li,
                            .products-slider-wrapper h3.products-slider-title,
                            .widget.testimonial-widget .testimonial-description,
                            .widget.yit_toggle_menu ul.menu > li,
                            .widget.yit-recent-comments div.comment,
                            .widget.yit_recent_reviews .review-content,
                            .related.products > h3
                            ',

    'border-1-all' =>   '.post.no-featured:not(.format-quote) .blog.big .yit_post_content,
                        .woocommerce ul.products li.product .product-wrapper,
                        ul.products li.product .thumb-wrapper.zoom .attachments-thumbnail .single-attachment-thumbnail,
                        .sbHolder .sbSelector,
                        .sbHolder .sbOptions,
                        #product-box .border.group,
                        .blog.small .post-wrapper,
                        #comments ol li .content,
                        .arrow:before, .arrow-right:before,
                        #comments ol li .avatar img,
                        .blog.big.single .yit_post_meta.last_block,
                        #commentform .comment-form-comment #comment,
                        div.pp_woocommerce .pp_gallery ul li a:hover,
                        div.pp_woocommerce .pp_gallery ul li.selected a,
                        .woocommerce-tabs #comments ol.commentlist li,
                        .arrow-down:before,
                        .woocommerce-tabs #review_form,
                        .woocommerce-tabs #review_form .comment-form-rating,
                        #commentform input:not([type=submit]),
                        .woocommerce input[type="text"],
                        .woocommerce input[type="password"],
                        .woocommerce input[type="email"],
                        .woocommerce input.input-text,
                        .woocommerce-page input.input-text,
                        #my-account-sidebar ul,
                        #my-account-sidebar .user-profile div.user-image,
                        #my-account-sidebar div.user-profile,
                        .meta.blog.big,
                        ul.products li.product .product-actions-wrapper .product-other-action.buttons_2 > div:first-child,
                        ul.products li.product .product-actions-wrapper .product-other-action.buttons_3 > div:first-child,
                        ul.products li.product .product-actions-wrapper .product-other-action.buttons_3 > div:last-child,
                        ul.products li.product .product-actions-wrapper .product-other-action.buttons_4 > div,
                        #popupWrap .product-share,
                        form.variations_form.cart td.value .select_option,
                        .single-product.woocommerce div.product div.summary div.product-share,
                        .woocommerce .quantity input.qty,
                        .woocommerce-page .quantity input.qty,
                        .woocommerce .quantity .minus, .woocommerce .quantity .plus,
                        .woocommerce-page .quantity .minus, .woocommerce-page .quantity .plus,
                        .woocommerce table.shop_table.cart thead,
                        #yith-wcwl-form table.shop_table thead,
                        .woocommerce .cart-collaterals,
                        input[type="password"],
                        input[type="text"],
                        #review-order-wrapper,
                        .woocommerce form .form-row textarea,
                        .woocommerce ul.order_details li,
                        .woocommerce-page ul.order_details li,
                        .widget.widget_search #searchform,
                        .woocommerce-product-search,
                        .products-slider-wrapper .es-nav-prev span,
                        .products-slider-wrapper .es-nav-next span,
                        .banner-container .banner-image,
                        .newsletter_form_email input.email-field,
                        .logos-slider .nav a.prev,
                        .logos-slider .nav a.next,
                        .contact-form li.textarea-field div.input-prepend textarea,
                        .contact-form li div.input-prepend input[type=text],
                        .contact-form li div.input-prepend input[type=password],
                        .contact-form li div.input-prepend select,
                        .yith-wpv-quick-info-wrapper textarea,
                        .wishlist-ask-an-estimate-popup textarea,
                        .widget.yith-woo-ajax-navigation ul.yith-wcan-color li a,
                        .widget.yith-woo-ajax-navigation ul.yith-wcan-label li a,
                        .member,
                        .blog-section-wrapper ul.blog_posts li div.blog_post,
                        .testimonial-wrapper,
                        #faqs-container .faq-wrapper,
                        #faqs-container .faq-icon,
                        .filters.faq li a,
                        .error-404-container .error-404-search input[type="text"],
                        .toggle,
                        .toggle .toggle-title span.fa.fa-plus.closed,
                        .toggle .toggle-title span.fa.fa-minus.opened,
                        .call-to-action-two,
                        .dropcap,
                        #show-category-product ul.products li a.product-category-link,
                        .categories-slider ul.products li a.product-category-link,
                        #show-category-product div.category-count:before,
                        .categories-slider div.category-count:before,
                        #primary .testimonials-slider ul.testimonial-content div.owl-prev,
                        #primary .testimonials-slider ul.testimonial-content div.owl-next,
                        .woocommerce .login-form-checkout,
                        .widget.featured-products .flex-direction-nav li a.flex-next,
                        .widget.featured-products .flex-direction-nav li a.flex-prev,
                        .widget.last-tweets .arrow-left,
                        .arrow-left:before,
                        .widget.testimonial-widget .ms-skin-default .ms-nav-next:after,
                        .widget.testimonial-widget .ms-skin-default .ms-nav-prev:after,
                        .sidebar .widget.newsletter-form .newsletter-section form input[type="text"],
                        .wpb_widgetised_column .widget.newsletter-form .newsletter-section form input[type="text"],
                        .widget.newsletter-form.with-border,
                        .categories-slider-wrapper .es-nav span,
                        .tabs-container ul.tabs li,
                        .woocommerce-tabs ul.tabs li,
                        .woocommerce-tabs ul.tabs li:last-child,
                        .blog.big .thumbnail,
                        .wpb_tabs .wpb_tabs_nav li
                        ',

    'border-2-bottom' =>    '.border-2-bottom',

    'border-2-top' => '.border-2-top',

    'border-2-all' =>  '.widget.yith-woo-ajax-navigation ul.yith-wcan-color li.chosen a,
                        .widget.yith-woo-ajax-navigation ul.yith-wcan-label li.chosen a,
                        .filters.faq li a.active,
                        #header a.cart-items > div',

    'a-tag' => 'a,
                a:visited,
                #header #welcome-menu-login .lost_password a,
                .nav  span.highlight,
                .box-content a h2,
                .woocommerce .login-form-checkout .woocommerce-info a,
                .testimonials-slider ul.testimonial-content li p.meta a',

    'a-tag-hover' => 'a:hover, a:active,
                        .product-actions-wrapper .product-other-action .yith-wcwl-add-to-wishlist:hover a,
                        .testimonials-slider ul.testimonial-content li p.meta a:hover,
                        .box-content a h2:hover,
                        .toggle .toggle-title h4:hover,
                        .toggle .toggle-title.tab-opened h4,
                        .toggle .toggle-title span.fa.fa-minus.opened:before,
                        #primary .testimonials-slider ul.testimonial-content div.owl-next:hover i:before,
                        #primary .testimonials-slider ul.testimonial-content div.owl-prev:hover i:before,
                        .product-actions-wrapper .product-other-action .compare-button:hover a,
                        .product-actions-wrapper .product-other-action .share-button:hover a,
                        .product-other-action div.yith-ywraq-add-button:hover a,
                        .woocommerce .product-other-action div.yith-ywraq-add-button:hover a.add-request-quote-button.button,
                        .product-other-action div.yith_ywraq_add_item_browse_message:hover a,
                        #product-box .product-actions .compare-button:hover a,
                        #product-box .product-actions .yith-wcwl-add-to-wishlist:hover a,
                        .single-product.woocommerce div.product div.summary .product-actions div.yith-wcwl-add-to-wishlist:hover a,
                        .single-product.woocommerce div.product div.summary .product-actions div.compare-button:hover a,
                        .woocommerce .product-actions div.yith-ywraq-add-button a:hover,
                        .product-actions div.yith_ywraq_add_item_browse_message a:hover,
                        .woocommerce .cart-collaterals .cart_totals h3,
                        #header #welcome-menu-login .lost_password a:hover,
                        .woocommerce table.cart td.product-name div.product-name-price div.product-name a:hover,
                        #product-nav > a:hover span.fa,
                        #my-account-sidebar ul li > a:hover,
                        #my-account-sidebar ul li > a.active,
                        #order_review_heading,
                        #payment h3,
                        .widget.yit-recent-posts .recent-post span.num-comments a:hover,
                        .widget.yit-recent-posts .recent-post span.author a:hover,
                        #inquiry-form .product-inquiry:hover h4,
                        #yith-wcwl-form table.shop_table td.product-name a:hover,
                        table.shop_table.my_account_orders tbody td.order-number a:hover,
                        table.shop_table.order_details tr.order_item td.product-name a:hover,
                        #list-or-grid a.active i,
                        #list-or-grid a:hover i,
                        #number-of-products a.active,
                        #number-of-products a:hover,
                         .comments-info-wrapper span.author a,
                        .woocommerce ul.product_list_widget li:hover a span.product_title,
                        .widget.yit-recent-posts .recent-post .text > div.post-content > a.title:hover,
                        form.variations_form.cart a.reset_variations:hover,
                        #faqs-container .faq-wrapper .faq-title:hover h4,
                        #faqs-container .faq-wrapper .faq-title:hover span.entypo,
                        #faqs-container .faq-wrapper .faq-title.active span.entypo,
                        .widget.woocommerce.widget_recent_reviews ul.product_list_widget li:hover a,
                        .widget.woocommerce.widget_recent_reviews ul.product_list_widget li a:hover,
                        #faqs-container .faq-wrapper .faq-title.active h4,
                        #show-category-product a.product-category-link:hover h4,
                        .products-slider.categories a.product-category-link:hover h4,
                        .woocommerce .login-form-checkout .woocommerce-info a:hover,
                        .widget.contact-info ul li:hover .info-container .contact_info_email h5,
                        .widget.yith-woo-ajax-navigation ul.yith-wcan-label li a:hover,
                        .widget.yith-woo-ajax-navigation ul.yith-wcan-label li.chosen a,
                        .widget.yith-woo-ajax-navigation ul.yith-wcan-list li:hover > *,
                        .widget.yith-woo-ajax-navigation ul.yith-wcan-list li.chosen > *,
                        .widget_product_categories ul a:hover,
                        #featured-slider .ms-nav-next:hover:after,
                        #featured-slider .ms-nav-prev:hover:after,
                        .widget_categories ul a:hover,
                        .widget_archive ul a:hover,
                        .widget_nav_menu ul a:hover,
                        .widget.widget_meta ul a:hover,
                        .widget_pages ul a:hover,
                        .widget.yit_products_category li:hover a span.product_title,
                        .widget.yit_toggle_menu ul.sub-menu li a:hover,
                        .widget.yit_toggle_menu ul.menu > li:hover > a,
                        .widget.yit_toggle_menu ul.menu > li.opened > a,
                        ul.blog_posts li div.blog_post .yit_post_meta span.info a:hover,
                        ul.blog_posts li div.blog_post .yit_post_meta span.title a:hover,
                        a:hover[class^=eg-portfolio-masonry],
                        .woocommerce ul.product_list_widget li a:hover,
                        .widget.testimonial-widget .ms-skin-default .ms-nav-next:hover:after,
                        .widget.testimonial-widget .ms-skin-default .ms-nav-prev:hover:after,
                        .widget.featured-products .flex-direction-nav li a:hover,
                        #product-nav a:hover span.glyphicon,
                        .modal-shortcode .modal-opener a:hover,
                        #primary .testimonials-slider ul.testimonial-content li p.meta span,
                        .widget.yit_recent_reviews .review-meta-avatar a:hover,
                        .widget.yit_recent_reviews span.entypo:hover,
                        .images-slider-sc .flex-direction-nav li a:hover:before,
                        .product-meta h3.product-name a:hover,
                        .woocommerce-product-rating a.woocommerce-review-link:hover,
                        .features-tab-container ul.features-tab-labels li.current-feature h4 a,
                        .features-tab-container ul.features-tab-labels li.current-feature:hover h4 a,
                        .features-tab-container ul.features-tab-labels li:hover h4 a,
                        .features-tab-container ul.features-tab-labels li h4 a:hover,
                        .sitemap a:hover,
                        .yith-woocompare-widget ul.products-list li a.title:hover,
                        .yith-woocompare-widget a.clear-all:hover,
                        .contact-info ul li:hover .info-container .contact_info_email h5,
                        .widget.widget_recent_entries ul li a:hover,
                        .widget h3 a.rsswidget:hover,
                        .widget.widget_rss ul li a.rsswidget:hover,
                        .widget_yith-wcwl-lists ul.dropdown > li.dropdown-section a:hover,
                        .product-categories a:hover',

    'p-tag' => 'p, body, time, dt, dd, td, th, address, .sbHolder a, #welcome-menu-login .lost_password a,
                          .testimonial-wrapper .testimonial-smallquote,
                          .nav span.highlight, .nav span.highlight-inverse,
                          table.shop_table.my_account_orders tbody td.order-number a,
                          .team-section .member-name,
                          .widget.testimonial-widget .ms-skin-default .ms-nav-next,
                          .widget.testimonial-widget .ms-skin-default .ms-nav-prev,
                          table.shop_table.order_details tr.order_item td.product-name a,
                          form.variations_form.cart a.reset_variations,
                          .filters-container ul.filters li .filter-category,
                          #portfolio_big li .info .categories a,
                          #portfolio_small li .info .categories a,
                          #portfolio_nav .title .categories a,
                          #portfolio_big li .info .portfolio_meta .meta_content a,
                          #portfolio_content .portfolio_meta .meta_content a,
                          #portfolio_nav div a .info .next_terms,
                          #portfolio_nav div a .info .prev_terms,
                          #portfolio_content .title,
                          #portfolio_content .content-style-social a,
                          #ship-to-different-address label,
                          .widget.widget_price_filter #min_price,
                          .widget.widget_price_filter #max_price,
                          .widget_price_filter .price_slider_amount .price_label,
                          .widget.widget_layered_nav ul li a,
                          ul.yith-wcan-list li a,
                          ul.yith-wcan-list li small,
                          .widget_product_categories ul a,
                          .widget_product_categories ul span,
                          #wp-calendar tfoot a,
                          .widget_categories ul a,
                          .widget_archive ul a,
                          .widget_nav_menu ul a,
                          .widget.widget_meta ul a,
                          .widget_pages ul a,
                          ul.short li,
                          ul.blog_posts li div.blog_post .yit_post_meta span.info a,
                          #sitewide-notice p,
                          .modal-shortcode .modal-opener a,
                          .widget.yit_recent_reviews .review-meta-avatar a,
                          .sitemap a,
                          .woocommerce-product-rating a.woocommerce-review-link,
                          .yith-woocompare-widget ul.products-list li a.title,
                          .yith-woocompare-widget a.clear-all,
                          .widget_yith-wcwl-lists ul.dropdown > li.dropdown-section a,
                          .yith_woocommerce_ajax_search #yith-s,
                          #yith-ajaxsearchform .search-navigation,
                          .yith_woocommerce_ajax_search .yith-wcas-search-list
                          '
);